bandwidth:
    default: 76

birthhighthreshold:
    default: -60.0

birthlowthreshold:
    default: -24.0

detectionthreshold:
    default: -96.0

fftsettings:
    default: "1024 -1 -1"

mintracklen:
    default: 15

trackfreqrange:
    default: 50.0

trackingmethod:
    # greedy 0
    # other one 1
    default: 0

trackmagrange:
    default: 15

trackprob:
    default: 0.5