
# Parameters are declared first with a node being its name.
# The default for this, and the type are specified in a child node from this.
parameter1:
    default: "4096 1024 4096"
    type: string

parameter2:
    default: 40
    type: int

parameter3:
    default: 13.32
    type: float
