source: ~/nhslice
folder: ~/waste

analysers:
    mfcc:
        fftsettings: "4096 1024 4096"
        numcoeffs: 13

    # stats:
    #     numderivs: 2
    #     flatten: True

    # dimension_reduction:
    #     components: 1
    
    # cluster:
    #     algorithm: AgglomCluster
    #     numclusters: 10
