source: ~/dev/ftis_example_project/audio
folder: ~/dev/ftis_example_project/analysis
mode: chain

analysers:
    fluid_noveltyslice:
        threshold: 0.5
    audio_explode:

    fluid_noveltyslice:
        threshold: 0.5
    audio_explode:
    
    mfcc:
        amplitude: True
    
    stats:
        numderivs: 3
        flatten: True

    dimension_reduction:
        scaling: standardise
        post_scaling: none
        components: 5
    
    cluster:


    