source: ~/dev/ftis_example_project/audio
folder: ~/dev/ftis_example_project/analysis
mode: chain

analysers:
    FluidLoudness:
        cache: True
    
    Stats:
        cache: True
        flatten: True

    DimensionReduction:
        cache: True
    
    AgglomerativeClustering:
        cache: False
        numclusters: 5
