source: ~/testfiles
folder: ~/ftisoutput

analysers:
    mfcc:
        fftsettings: "2048 1024 2048"
        numcoeffs: 13
        numbands : 20

    stats:
        numderivs: 3

    dr:
        algorithm: UMAP

    cluster:
        algorithm: HDBSCAN

