source: ~/dev/ftis_example_project/audio
folder: ~/dev/ftis_example_project/analysis
mode: batch
analysers:
    FluidMFCC:
        cache: True
    FluidSines:
        cache: True
    FluidLoudness:
        cache: True
    FluidNoveltyslice:
        cache: True
    FluidTransients:
        cache: True
