source: ~/dev/ftis_example_project/audio
folder: ~/dev/ftis_example_project/analysis
mode: batch
cache: True

analysers:
    FluidMFCC:
        numbands: 10
    FluidSines:
    FluidLoudness:
    FluidNoveltyslice:
    FluidTransients: