input_scaling:
    # Scaling that is applied to the input data prior to clustering
    default: standardise
    options: 
        standardise
        normalise

windowsize:
    default: 5

numclusters: # only used if the algorithm requires a number of clusters
    default: 4
