blocksize:
    default: 256

clumplength:
    default: 25

order:
    default: 20

padsize:
    default: 128

skew:
    default: 0.0

threshback:
    default: 1.1

threshfwd:
    default: 2.0

windowsize:
    default: 14